// <auto-generated />
using HomeEnergyApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeEnergyApi.Migrations
{
    [DbContext(typeof(HomeDbContext))]
    partial class HomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HomeEnergyApi.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.HomeUsageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonthlyElectricUsage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId")
                        .IsUnique();

                    b.ToTable("HomeUsageDatas");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.HomeUtilityProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilityProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UtilityProviderId");

                    b.ToTable("HomeUtilityProviders");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.UtilityProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ProvidedUtilities")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UtilityProviders");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.HomeUsageData", b =>
                {
                    b.HasOne("HomeEnergyApi.Models.Home", "Home")
                        .WithOne("HomeUsageData")
                        .HasForeignKey("HomeEnergyApi.Models.HomeUsageData", "HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.HomeUtilityProvider", b =>
                {
                    b.HasOne("HomeEnergyApi.Models.Home", "Home")
                        .WithMany("HomeUtilityProviders")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeEnergyApi.Models.UtilityProvider", "UtilityProvider")
                        .WithMany("HomeUtilityProviders")
                        .HasForeignKey("UtilityProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("UtilityProvider");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.Home", b =>
                {
                    b.Navigation("HomeUsageData");

                    b.Navigation("HomeUtilityProviders");
                });

            modelBuilder.Entity("HomeEnergyApi.Models.UtilityProvider", b =>
                {
                    b.Navigation("HomeUtilityProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
